import { FeedSource } from "./types";

export const defaultFeeds: FeedSource[] = [
  // ── AGRO ──────────────────────────────────────────────
  {
    id: "canalrural",
    name: "Canal Rural",
    url: "https://www.canalrural.com.br/feed/",
    category: "agro",
    enabled: true,
    isDefault: true,
  },
  {
    id: "agrolink",
    name: "Agrolink",
    url: "https://www.agrolink.com.br/rss/noticias.xml",
    category: "agro",
    enabled: true,
    isDefault: true,
  },
  {
    id: "noticiasagricolas",
    name: "Notícias Agrícolas",
    url: "https://www.noticiasagricolas.com.br/rss/noticias.xml",
    category: "agro",
    enabled: true,
    isDefault: true,
  },
  {
    id: "revistagloborural",
    name: "Globo Rural",
    url: "https://revistapegn.globo.com/rss/feed.xml",
    category: "agro",
    enabled: true,
    isDefault: true,
  },
  {
    id: "sucessonocampo",
    name: "Sucesso no Campo",
    url: "https://www.sucessonocampo.com.br/feed/",
    category: "agro",
    enabled: true,
    isDefault: true,
  },

  // ── FINANÇAS ──────────────────────────────────────────
  {
    id: "bloomberg",
    name: "Bloomberg",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "reuters",
    name: "Reuters",
    url: "https://www.rss.reuters.com/news/businessNews",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "ft",
    name: "Financial Times",
    url: "https://www.ft.com/rss/home",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "infomoney",
    name: "InfoMoney",
    url: "https://www.infomoney.com.br/feed/",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "valoreconomico",
    name: "Valor Econômico",
    url: "https://pox.globo.com/rss/valor/",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "exame",
    name: "Exame",
    url: "https://exame.com/feed/",
    category: "business",
    enabled: true,
    isDefault: true,
  },
  {
    id: "investingnews",
    name: "Investing.com BR",
    url: "https://br.investing.com/rss/news.rss",
    category: "business",
    enabled: true,
    isDefault: true,
  },

  // ── GEOPOLÍTICA ───────────────────────────────────────
  {
    id: "bbc-mundo",
    name: "BBC News",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    category: "brazil",
    enabled: true,
    isDefault: true,
  },
  {
    id: "aljazeera",
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    category: "brazil",
    enabled: true,
    isDefault: true,
  },
  {
    id: "foreignaffairs",
    name: "Foreign Affairs",
    url: "https://www.foreignaffairs.com/rss.xml",
    category: "brazil",
    enabled: true,
    isDefault: true,
  },
  {
    id: "folha",
    name: "Folha de S.Paulo — Mundo",
    url: "https://feeds.folha.uol.com.br/mundo/rss091.xml",
    category: "brazil",
    enabled: true,
    isDefault: true,
  },
];
